name: Test
on:
  pull_request:
    branches:
      - master
    paths:
      - '**.css'
      - '**.scss'

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/stylelint@master